### ISSUE TITLE
EBI jumphost doesn't seem to like these keys

### ISSUE THREAD

**Issue by darmach** [stackhpc/terraform-bastion#88]
I'm unable to add the new key to EBI jumphost, one can not just edit the authorized keys:
```
Note that OpenSSH and SSH1 keys consist only one long line, so take care to
avoid having line feeds in the key.
Type in the key, end with CTRL-D or with dot (.) on an empty line:
sk-ssh-ed25519@openssh.com xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx darmach StackHPC key - 2024-07-24
.


Invalid key, key not added
```

**Comment by technowhizz** [comment]
is the node RL-9 ? Dont you have to make changes if its not 🤷  not 100% sure

**Comment by darmach** [comment]
It's an appliance, no shell access, just a basic ui to add and list keys

**Comment by cityofships** [comment]
> I'm unable to add the new key to EBI jumphost, one can not just edit the authorized keys:
> 
> ```
> Note that OpenSSH and SSH1 keys consist only one long line, so take care to
> avoid having line feeds in the key.
> Type in the key, end with CTRL-D or with dot (.) on an empty line:
> sk-ssh-ed25519@openssh.com xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx darmach StackHPC key - 2024-07-24
> .
> 
> 
> Invalid key, key not added
> ```

That jumphost is kind of special. For me it was not accepting ED25519 either, only RSA. Perhaps try via their help desk.

That being said, issue unrelated to this repository, hence closing.
